language: java
jdk: oraclejdk7
 
before_install:
  # required libs for android build tools
  - sudo apt-get update
  - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch build-essential git autoconf libtool pkg-config gperf gettext yasm
  # newest Android NDK
  - if [ `uname -m` = x86_64]; then wget http://dl.google.com/android/ndk/android-ndk-r9c-linux-x86_64.tar.bz2 -O ndk.tgz; else wget http://dl.google.com/android/ndk/android-ndk-r9c-linux-x86.tar.bz2 -O ndk.tgz; fi
  - tar -xf ndk.tgz
  - export ANDROID_NDK=`pwd`/android-ndk-r9c
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r9c
  - bash init_update_libs.sh

script: "./android_build.sh"

after_script:
  - sh wrap_release.sh

deploy:
  provider: releases
  api_key:
    - secure: F641jf9qyiyGe7lUV5md0dq/UN3FdOY3FDcFaRD3JlJoLuxuZT5ghVvRPtqNYUmmbvYYUpQ7mMqww3KyiGHoFYAljlUBXWE5HFVXy54qvhyjUyWKUxiAmXaqZE8xCXEdS3t3MkOeb9jxq2vCGJMCelG6Iq05ts4cMCw3r/2gEKE=
  file: "ffmpeg-android.tar.gz"
  skip_cleanup: true
  on:
    tags: true
